services:
  - type: worker
    name: owobot-render
    runtime: python
    repo: https://github.com/diddo317-alt/owobot-render
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
